name: Exchange scraper

on:
  schedule:
    - cron: "0 3,15 * * *"

  workflow_dispatch:


jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: |
          pip install -r ayirboshlash/requirements.txt
          playwright install chromium


      - name: Run scraper
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}

        run: |
          cd ayirboshlash
          python main.py
